export const content: string;
export const section: string;
export const title: string;
export const count: string;
export const issues: string;
export const issue: string;
export const icon: string;
export const issueName: string;
export const description: string;
