export const layoutContent: string;
export const projectName: string;
export const buttons: string;
export const changeIssueStatus: string;
export const people: string;
export const assignee: string;
export const form: string;
export const author: string;
export const tabs: string;
